apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: cns-bucket-instance
  namespace: test-ns
spec:
  clusterServiceClassExternalName: cns-bucket-service
  clusterServicePlanExternalName: default
  parameters:
    bucketName: "cns-bucket-demo" # Optional
